[package]
name = "nft-stacking-meta"
version = "0.0.0"
edition = "2018"
publish = false
authors = [ "you",]

[dev-dependencies]

[dependencies.nft-stacking]
path = ".."

[dependencies.elrond-wasm-debug]
version = "0.34.0"
